apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: crossplane-system

resources:
  - s3-bucket.yaml
  - configmap.yaml

commonLabels:
  app.kubernetes.io/managed-by: crossplane
  example: test-manifests
